export const JOURNAL_EVENT_TYPES = {
  INVITE_CREATED: 'INVITE_CREATED',
  INVITE_REDEEMED: 'INVITE_REDEEMED',
  CHECKIN_OPENED: 'CHECKIN_OPENED',
  NAME_SET: 'NAME_SET',
  DEVICE_PREVIEW: 'DEVICE_PREVIEW',
  PROVIDER_JOINED: 'PROVIDER_JOINED',
  PROVIDER_LEFT: 'PROVIDER_LEFT',
  MEDIA_STARTED: 'MEDIA_STARTED',
  MEDIA_STOPPED: 'MEDIA_STOPPED',
  PARTICIPANT_ALONE: 'PARTICIPANT_ALONE',
  FORM_ASSIGNED: 'FORM_ASSIGNED',
  FORM_SUBMITTED: 'FORM_SUBMITTED',
  NOTE_ADDED: 'NOTE_ADDED',
  CHAT_MESSAGE: 'CHAT_MESSAGE',
  RECONNECT_SUCCESS: 'RECONNECT_SUCCESS',
  RECONNECT_FAILED: 'RECONNECT_FAILED',
  SECOND_DEVICE_ATTEMPT: 'SECOND_DEVICE_ATTEMPT',
  HANDOFF_ISSUED: 'HANDOFF_ISSUED',
  HANDOFF_REDEEMED: 'HANDOFF_REDEEMED',
  ENCOUNTER_ENDED: 'ENCOUNTER_ENDED',
} as const

export type JournalEventType = typeof JOURNAL_EVENT_TYPES[keyof typeof JOURNAL_EVENT_TYPES]

export const RRT_TTL_HOURS = 24
export const ROOM_IDLE_TIMEOUT_MINUTES = 60

export const PROVIDER_CREDENTIALS = {
  email: 'provider@demo.test',
  password: 'demo123',
  id: 'provider-demo-001',
  name: 'Dr. Demo Provider',
  room: 'demo-room',
}
